// Auto-generated by scripts/generate_ts_types.py. Do not edit.
/* eslint-disable */
/* prettier-ignore */

export type JSONValue = string | number | boolean | null | JSONArray | JSONObject;
export type JSONObject = { [key: string]: JSONValue };
export type JSONArray = JSONValue[];

export interface ActivityFeedItem {
  message: string;
  category: string;
  icon?: string | null;
  created_at: string;
}

export interface AddToSpaceRequest {
  catalog_entry_id: string;
  research_space_id: string;
  source_config?: Record<string, unknown>;
}

export interface AdvancedQueryParameters {
  gene_symbol?: string | null;
  search_term?: string | null;
  date_from?: string | null;
  date_to?: string | null;
  publication_types?: string[];
  languages?: string[];
  sort_by?: 'relevance' | 'publication_date' | 'author' | 'journal' | 'title';
  max_results?: number;
  additional_terms?: string | null;
  variation_types?: string[];
  clinical_significance?: string[];
  is_reviewed?: boolean | null;
  organism?: string | null;
}

export interface AdvancedQueryParametersModel {
  gene_symbol?: string | null;
  search_term?: string | null;
  date_from?: string | null;
  date_to?: string | null;
  publication_types?: string[];
  languages?: string[];
  sort_by?: string | null;
  max_results?: number;
  additional_terms?: string | null;
  variation_types?: string[];
  clinical_significance?: string[];
  is_reviewed?: boolean | null;
  organism?: string | null;
}

export interface AuthorInfo {
  name: string;
  first_name?: string | null;
  last_name?: string | null;
  affiliation?: string | null;
  orcid?: string | null;
}

export interface CatalogAIProfile {
  is_ai_managed?: boolean;
  source_type?: string;
  agent_prompt?: string;
  use_research_space_context?: boolean;
  model_id?: string | null;
  default_query?: string | null;
}

export interface CatalogDiscoveryDefaults {
  schedule_enabled?: boolean;
  schedule_frequency?: unknown;
  schedule_timezone?: string;
  ai_profile?: CatalogAIProfile;
}

export interface CreatePubmedPresetRequest {
  name: string;
  description?: string | null;
  scope?: 'user' | 'space';
  parameters: AdvancedQueryParameters;
  research_space_id?: string | null;
}

export interface CreatePubmedPresetRequestModel {
  name: string;
  description?: string | null;
  scope?: 'user' | 'space';
  research_space_id?: string | null;
  parameters: AdvancedQueryParametersModel;
}

export interface CreateSessionRequest {
  name?: string;
  research_space_id?: string | null;
  initial_parameters?: AdvancedQueryParametersModel;
}

export interface DashboardSummary {
  pending_count: number;
  approved_count: number;
  rejected_count: number;
  total_items: number;
  entity_counts?: Record<string, number>;
}

export interface DataDiscoverySessionResponse {
  id: string;
  owner_id: string;
  research_space_id: string | null;
  name: string;
  current_parameters: AdvancedQueryParametersModel;
  selected_sources: string[];
  tested_sources: string[];
  total_tests_run: number;
  successful_tests: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  last_activity_at: string;
}

export interface DiscoveryPresetResponse {
  id: string;
  name: string;
  description: string | null;
  provider: 'pubmed';
  scope: 'user' | 'space';
  research_space_id: string | null;
  parameters: AdvancedQueryParametersModel;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface DiscoverySearchJobResponse {
  id: string;
  owner_id: string;
  session_id: string | null;
  provider: 'pubmed';
  status: 'queued' | 'running' | 'completed' | 'failed';
  query_preview: string;
  parameters: AdvancedQueryParametersModel;
  total_results: number;
  result_metadata: Record<string, unknown>;
  error_message: string | null;
  storage_key: string | null;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
}

export interface ErrorDetail {
  field?: string | null;
  message: string;
  code?: string | null;
}

export interface ErrorResponse {
  error: string;
  message: string;
  details?: ErrorDetail[] | null;
  request_id?: string | null;
}

export interface EvidenceCreate {
  variant_id: string;
  phenotype_id: string;
  description: string;
  summary?: string | null;
  evidence_level?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  evidence_type?: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion';
  publication_id?: string | null;
  confidence_score?: number;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed?: boolean;
  review_date?: string | null;
  reviewer_notes?: string | null;
}

export interface EvidenceResponse {
  id: number;
  variant_id: string;
  phenotype_id: string;
  publication_id?: string | null;
  description: string;
  summary?: string | null;
  evidence_level: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  evidence_type: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion';
  confidence_score: number;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed: boolean;
  review_date?: string | null;
  reviewer_notes?: string | null;
  created_at: string;
  updated_at: string;
  variant?: VariantLinkSummary | null;
  phenotype?: PhenotypeSummary | null;
  publication?: PublicationSummary | null;
}

export interface EvidenceSummaryResponse {
  id?: number | null;
  evidence_level: string;
  evidence_type: string;
  description: string;
  reviewed: boolean;
}

export interface EvidenceUpdate {
  description?: string | null;
  summary?: string | null;
  evidence_level?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven' | null;
  evidence_type?: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion' | null;
  publication_id?: string | null;
  confidence_score?: number | null;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed?: boolean | null;
  review_date?: string | null;
  reviewer_notes?: string | null;
}

export interface ExecuteQueryTestRequest {
  session_id: string;
  catalog_entry_id: string;
  timeout_seconds?: number;
  parameters?: AdvancedQueryParameters | null;
}

export interface ExecuteTestRequest {
  catalog_entry_id: string;
  timeout_seconds?: number;
  parameters?: AdvancedQueryParametersModel | null;
}

export interface ExportEntityInfo {
  type: string;
  description: string;
}

export interface ExportOptionsResponse {
  entity_type: string;
  export_formats: string[];
  compression_formats: string[];
  info: Record<string, unknown>;
}

export interface ExportableEntitiesResponse {
  exportable_entities: ExportEntityInfo[];
  supported_formats: string[];
  supported_compression: string[];
  usage: UsageInfo;
}

export interface ExtractionFactResponse {
  fact_type: unknown;
  value: string;
  normalized_id?: string | null;
  source?: string | null;
  attributes?: Record<string, unknown> | null;
}

export interface GeneCreate {
  symbol: string;
  name?: string | null;
  description?: string | null;
  gene_type?: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown';
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
}

export interface GenePhenotypeSummary {
  phenotype_id: string;
  name: string;
}

export interface GeneResponse {
  id: number;
  gene_id: string;
  symbol: string;
  name?: string | null;
  description?: string | null;
  gene_type: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown';
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
  created_at: string;
  updated_at: string;
  variant_count?: number;
  phenotype_count?: number;
  variants?: VariantSummaryResponse[] | null;
  phenotypes?: GenePhenotypeSummary[] | null;
}

export interface GeneSummary {
  id?: number | null;
  gene_id?: string | null;
  symbol?: string | null;
  name?: string | null;
}

export interface GeneUpdate {
  name?: string | null;
  description?: string | null;
  gene_type?: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown' | null;
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
}

export interface HealthComponent {
  status: string;
  message?: string | null;
  details?: Record<string, unknown> | null;
}

export interface HealthResponse {
  status: string;
  timestamp: string;
  version: string;
  uptime?: string | null;
  components?: Record<string, HealthComponent> | null;
}

export interface MechanismCreate {
  name: string;
  description: string;
  evidence_tier: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score?: number;
  source?: string;
  lifecycle_state?: 'draft' | 'reviewed' | 'canonical' | 'deprecated';
  protein_domains?: ProteinDomainPayload[];
  phenotype_ids: number[];
}

export interface MechanismResponse {
  id: number;
  name: string;
  description?: string | null;
  evidence_tier: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score: number;
  source: string;
  lifecycle_state: 'draft' | 'reviewed' | 'canonical' | 'deprecated';
  protein_domains: ProteinDomainPayload[];
  phenotype_ids: number[];
  phenotype_count: number;
  created_at: string;
  updated_at: string;
}

export interface MechanismUpdate {
  name?: string | null;
  description?: string | null;
  evidence_tier?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven' | null;
  confidence_score?: number | null;
  source?: string | null;
  lifecycle_state?: 'draft' | 'reviewed' | 'canonical' | 'deprecated' | null;
  protein_domains?: ProteinDomainPayload[] | null;
  phenotype_ids?: number[] | null;
}

export interface OrchestratedSessionState {
  session: DataDiscoverySessionResponse;
  capabilities: SourceCapabilitiesDTO;
  validation?: ValidationResultDTO;
  view_context: ViewContextDTO;
}

export interface PaginatedResponse<T = unknown> {
  items: T[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
  has_next: boolean;
  has_prev: boolean;
}

export interface PaginationParams {
  page?: number;
  per_page?: number;
  sort_by?: string | null;
  sort_order?: string;
}

export interface PhenotypeCategoryResult {
  category: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  total_results: number;
  results: PhenotypeResponse[];
}

export interface PhenotypeCreate {
  hpo_id: string;
  hpo_term: string;
  name: string;
  definition?: string | null;
  synonyms?: string[] | null;
  category?: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  parent_hpo_id?: string | null;
  is_root_term?: boolean;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
}

export interface PhenotypeEvidenceResponse {
  phenotype_id: number;
  total_count: number;
  evidence?: EvidenceSummaryResponse[];
}

export interface PhenotypeResponse {
  id: number;
  hpo_id: string;
  hpo_term: string;
  name: string;
  definition?: string | null;
  synonyms?: string[] | null;
  category: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  parent_hpo_id?: string | null;
  is_root_term: boolean;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  variant_count?: number;
  parent_phenotype?: PhenotypeSummary | null;
  child_phenotypes?: PhenotypeSummary[] | null;
  evidence?: EvidenceSummaryResponse[] | null;
}

export interface PhenotypeSearchResult {
  query: string;
  total_results: number;
  results: PhenotypeResponse[];
}

export interface PhenotypeStatisticsResponse {
  total_phenotypes: number;
  root_terms: number;
  phenotypes_with_evidence: number;
}

export interface PhenotypeSummary {
  id?: number | null;
  hpo_id?: string | null;
  name?: string | null;
}

export interface PhenotypeUpdate {
  name?: string | null;
  definition?: string | null;
  synonyms?: string[] | null;
  category?: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other' | null;
  parent_hpo_id?: string | null;
  is_root_term?: boolean | null;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
}

export interface ProteinDomainCoordinate {
  x: number;
  y: number;
  z: number;
  confidence?: number | null;
}

export interface ProteinDomainPayload {
  name: string;
  source_id?: string | null;
  start_residue: number;
  end_residue: number;
  domain_type?: unknown;
  description?: string | null;
  coordinates?: ProteinDomainCoordinate[] | null;
}

export interface PublicationCreate {
  title: string;
  authors: AuthorInfo[];
  journal: string;
  publication_year: number;
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  publication_type?: 'journal_article' | 'review_article' | 'case_report' | 'conference_abstract' | 'book_chapter' | 'thesis' | 'preprint';
  abstract?: string | null;
  keywords?: string[] | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed?: boolean;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access?: boolean;
}

export interface PublicationExtractionDocumentResponse {
  extraction_id: string;
  document_reference: string;
  url: string;
}

export interface PublicationExtractionResponse {
  id: string;
  publication_id?: number | null;
  pubmed_id?: string | null;
  source_id: string;
  ingestion_job_id: string;
  queue_item_id: string;
  status: 'completed' | 'failed' | 'skipped';
  extraction_version: number;
  processor_name: string;
  processor_version?: string | null;
  text_source: string;
  document_reference?: string | null;
  facts?: ExtractionFactResponse[];
  metadata?: Record<string, unknown>;
  extracted_at: string;
  created_at: string;
  updated_at: string;
}

export interface PublicationResponse {
  id: number;
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  title: string;
  authors: AuthorInfo[];
  journal: string;
  publication_year: number;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  publication_type: 'journal_article' | 'review_article' | 'case_report' | 'conference_abstract' | 'book_chapter' | 'thesis' | 'preprint';
  abstract?: string | null;
  keywords?: string[] | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed: boolean;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access: boolean;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  evidence?: EvidenceResponse[] | null;
}

export interface PublicationSummary {
  id?: number | null;
  title?: string | null;
  pubmed_id?: string | null;
  doi?: string | null;
}

export interface PublicationUpdate {
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  title?: string | null;
  authors?: AuthorInfo[] | null;
  abstract?: string | null;
  keywords?: string[] | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed?: boolean | null;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access?: boolean | null;
}

export interface PubmedDownloadRequestModel {
  job_id: string;
  article_id: string;
}

export interface QueryParameterCapabilities {
  supports_date_range?: boolean;
  supports_publication_types?: boolean;
  supports_language_filter?: boolean;
  supports_sort_options?: boolean;
  supports_additional_terms?: boolean;
  max_results_limit?: number;
  supported_storage_use_cases?: 'pdf' | 'export' | 'raw_source' | 'document_content' | 'backup'[];
  supports_variation_type?: boolean;
  supports_clinical_significance?: boolean;
  supports_review_status?: boolean;
  supports_organism?: boolean;
  discovery_defaults?: CatalogDiscoveryDefaults;
}

export interface QueryParameters {
  gene_symbol?: string | null;
  search_term?: string | null;
}

export interface QueryParametersModel {
  gene_symbol?: string | null;
  search_term?: string | null;
}

export interface QueryTestResultResponse {
  id: string;
  catalog_entry_id: string;
  session_id: string;
  parameters: AdvancedQueryParametersModel;
  status: 'pending' | 'success' | 'error' | 'timeout' | 'validation_failed';
  response_data: Record<string, unknown> | null;
  response_url: string | null;
  error_message: string | null;
  execution_time_ms: number | null;
  data_quality_score: number | null;
  started_at: string;
  completed_at: string | null;
}

export interface RunPubmedSearchRequestModel {
  session_id?: string | null;
  parameters: AdvancedQueryParametersModel;
}

export interface SourceCapabilitiesDTO {
  supports_gene_search?: boolean;
  supports_term_search?: boolean;
  supported_parameters?: string[];
  max_results_limit?: number;
}

export interface SourceCatalogEntry {
  id: string;
  name: string;
  category: string;
  subcategory: string | null;
  description: string;
  source_type: 'file_upload' | 'api' | 'database' | 'web_scraping' | 'pubmed' | 'clinvar';
  param_type: 'gene' | 'term' | 'gene_and_term' | 'none' | 'api';
  is_active: boolean;
  requires_auth: boolean;
  usage_count: number;
  success_rate: number;
  tags: string[];
  capabilities: QueryParameterCapabilities;
}

export interface SourceCatalogResponse {
  id: string;
  name: string;
  category: string;
  subcategory: string | null;
  description: string;
  source_type: 'file_upload' | 'api' | 'database' | 'web_scraping' | 'pubmed' | 'clinvar';
  param_type: 'gene' | 'term' | 'gene_and_term' | 'none' | 'api';
  is_active: boolean;
  requires_auth: boolean;
  usage_count: number;
  success_rate: number;
  tags: string[];
  capabilities: QueryParameterCapabilities;
}

export interface StatementCreate {
  title: string;
  summary: string;
  evidence_tier?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score?: number;
  status?: 'draft' | 'under_review' | 'well_supported';
  source?: string;
  protein_domains?: ProteinDomainPayload[];
  phenotype_ids?: number[];
}

export interface StatementResponse {
  id: number;
  title: string;
  summary: string;
  evidence_tier: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score: number;
  status: 'draft' | 'under_review' | 'well_supported';
  source: string;
  protein_domains: ProteinDomainPayload[];
  phenotype_ids: number[];
  phenotype_count: number;
  promoted_mechanism_id?: number | null;
  created_at: string;
  updated_at: string;
}

export interface StatementUpdate {
  title?: string | null;
  summary?: string | null;
  evidence_tier?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven' | null;
  confidence_score?: number | null;
  status?: 'draft' | 'under_review' | 'well_supported' | null;
  source?: string | null;
  protein_domains?: ProteinDomainPayload[] | null;
  phenotype_ids?: number[] | null;
  promoted_mechanism_id?: number | null;
}

export interface StorageOperationResponse {
  id: string;
  configuration_id: string;
  key: string;
  status: 'success' | 'failed' | 'pending';
  created_at: string;
  metadata: Record<string, unknown>;
}

export interface UpdateParametersRequest {
  parameters: AdvancedQueryParametersModel;
}

export interface UpdateSelectionRequest {
  source_ids?: string[];
}

export interface UsageInfo {
  endpoint: string;
  description: string;
}

export interface ValidationIssueDTO {
  code: string;
  message: string;
  severity?: string;
  field?: string | null;
}

export interface ValidationResultDTO {
  is_valid: boolean;
  issues?: ValidationIssueDTO[];
}

export interface VariantCreate {
  gene_id: string;
  chromosome: string;
  position: number;
  reference_allele: string;
  alternate_allele: string;
  clinvar_id?: string | null;
  variant_id?: string | null;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type?: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown';
  clinical_significance?: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided';
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
}

export interface VariantLinkSummary {
  id?: number | null;
  variant_id?: string | null;
  clinvar_id?: string | null;
  gene_symbol?: string | null;
}

export interface VariantResponse {
  id: number;
  variant_id: string;
  clinvar_id?: string | null;
  gene_id: string;
  gene_symbol: string;
  chromosome: string;
  position: number;
  reference_allele: string;
  alternate_allele: string;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown';
  clinical_significance: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided';
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  gene?: GeneSummary | null;
  evidence?: EvidenceSummaryResponse[] | null;
}

export interface VariantSummaryResponse {
  variant_id: string;
  clinvar_id?: string | null;
  chromosome: string;
  position: number;
  clinical_significance?: string | null;
}

export interface VariantUpdate {
  clinvar_id?: string | null;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type?: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown' | null;
  clinical_significance?: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided' | null;
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
}

export interface ViewContextDTO {
  selected_count: number;
  total_available: number;
  can_run_search: boolean;
  categories?: Record<string, number>;
}
