// Auto-generated by scripts/generate_ts_types.py. Do not edit.
/* eslint-disable */
/* prettier-ignore */

export type JSONValue = string | number | boolean | null | JSONArray | JSONObject;
export type JSONObject = { [key: string]: JSONValue };
export type JSONArray = JSONValue[];

export interface ActivityFeedItem {
  message: string;
  category: string;
  icon?: string | null;
  created_at: string;
}

export interface AddToSpaceRequest {
  catalog_entry_id: string;
  research_space_id: string;
  source_config?: Record<string, unknown>;
}

export interface AdvancedQueryParameters {
  gene_symbol?: string | null;
  search_term?: string | null;
  date_from?: string | null;
  date_to?: string | null;
  publication_types?: string[];
  languages?: string[];
  sort_by?: 'relevance' | 'publication_date' | 'author' | 'journal' | 'title';
  max_results?: number;
  additional_terms?: string | null;
  variation_types?: string[];
  clinical_significance?: string[];
  is_reviewed?: boolean | null;
  organism?: string | null;
}

export interface AdvancedQueryParametersModel {
  gene_symbol?: string | null;
  search_term?: string | null;
  date_from?: string | null;
  date_to?: string | null;
  publication_types?: string[];
  languages?: string[];
  sort_by?: string | null;
  max_results?: number;
  additional_terms?: string | null;
  variation_types?: string[];
  clinical_significance?: string[];
  is_reviewed?: boolean | null;
  organism?: string | null;
}

export interface AuthorInfo {
  name: string;
  first_name?: string | null;
  last_name?: string | null;
  affiliation?: string | null;
  orcid?: string | null;
}

export interface CatalogAIProfile {
  is_ai_managed?: boolean;
  source_type?: string;
  agent_prompt?: string;
  use_research_space_context?: boolean;
  model_id?: string | null;
  default_query?: string | null;
}

export interface CatalogDiscoveryDefaults {
  schedule_enabled?: boolean;
  schedule_frequency?: unknown;
  schedule_timezone?: string;
  ai_profile?: CatalogAIProfile;
}

export interface ClaimParticipantBackfillRequest {
  dry_run?: boolean;
  limit?: number;
  offset?: number;
}

export interface ClaimParticipantBackfillResponse {
  operation_run_id: string;
  scanned_claims: number;
  created_participants: number;
  skipped_existing: number;
  unresolved_endpoints: number;
  dry_run: boolean;
}

export interface ClaimParticipantCoverageResponse {
  total_claims: number;
  claims_with_any_participants: number;
  claims_with_subject: number;
  claims_with_object: number;
  unresolved_subject_endpoints: number;
  unresolved_object_endpoints: number;
  unresolved_endpoint_rate: number;
}

export interface ClaimParticipantListResponse {
  claim_id: string;
  participants: ClaimParticipantResponse[];
  total: number;
}

export interface ClaimParticipantResponse {
  id: string;
  claim_id: string;
  research_space_id: string;
  label: string | null;
  entity_id: string | null;
  role: string;
  position: number | null;
  qualifiers: Record<string, unknown>;
  created_at: string;
}

export interface ClaimRelationCreateRequest {
  source_claim_id: string;
  target_claim_id: string;
  relation_type: string;
  agent_run_id?: string | null;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  confidence?: number;
  review_status?: string;
  evidence_summary?: string | null;
  metadata?: Record<string, unknown>;
}

export interface ClaimRelationListResponse {
  claim_relations: ClaimRelationResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface ClaimRelationResponse {
  id: string;
  research_space_id: string;
  source_claim_id: string;
  target_claim_id: string;
  relation_type: string;
  agent_run_id: string | null;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  confidence: number;
  review_status: string;
  evidence_summary: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface ClaimRelationReviewUpdateRequest {
  review_status: string;
}

export interface ConceptAliasListResponse {
  concept_aliases: ConceptAliasResponse[];
  total: number;
}

export interface ConceptAliasResponse {
  id: number;
  concept_member_id: string;
  research_space_id: string;
  domain_context: string;
  alias_label: string;
  alias_normalized: string;
  source: string | null;
  review_status: unknown;
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptDecisionListResponse {
  concept_decisions: ConceptDecisionResponse[];
  total: number;
}

export interface ConceptDecisionResponse {
  id: string;
  research_space_id: string;
  concept_set_id: string | null;
  concept_member_id: string | null;
  concept_link_id: string | null;
  decision_type: unknown;
  decision_status: unknown;
  proposed_by: string;
  decided_by: string | null;
  confidence: number | null;
  rationale: string | null;
  evidence_payload: Record<string, unknown>;
  decision_payload: Record<string, unknown>;
  harness_outcome: unknown | null;
  decided_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptDecisionStatusRequest {
  decision_status: unknown;
}

export interface ConceptMemberListResponse {
  concept_members: ConceptMemberResponse[];
  total: number;
}

export interface ConceptMemberResponse {
  id: string;
  concept_set_id: string;
  research_space_id: string;
  domain_context: string;
  canonical_label: string;
  normalized_label: string;
  sense_key: string;
  dictionary_dimension: string | null;
  dictionary_entry_id: string | null;
  is_provisional: boolean;
  metadata_payload: Record<string, unknown>;
  review_status: unknown;
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptPolicyResponse {
  id: string;
  research_space_id: string;
  profile_name: string;
  mode: unknown;
  minimum_edge_confidence: number;
  minimum_distinct_documents: number;
  allow_generic_relations: boolean;
  max_edges_per_document: number | null;
  policy_payload: Record<string, unknown>;
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptSetListResponse {
  concept_sets: ConceptSetResponse[];
  total: number;
}

export interface ConceptSetResponse {
  id: string;
  research_space_id: string;
  name: string;
  slug: string;
  domain_context: string;
  description: string | null;
  review_status: unknown;
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateManualHypothesisRequest {
  statement: string;
  rationale: string;
  seed_entity_ids?: string[];
  source_type?: string;
}

export interface CreatePubmedPresetRequest {
  name: string;
  description?: string | null;
  scope?: 'user' | 'space';
  parameters: AdvancedQueryParameters;
  research_space_id?: string | null;
}

export interface CreatePubmedPresetRequestModel {
  name: string;
  description?: string | null;
  scope?: 'user' | 'space';
  research_space_id?: string | null;
  parameters: AdvancedQueryParametersModel;
}

export interface CreateSessionRequest {
  name?: string;
  research_space_id?: string | null;
  initial_parameters?: AdvancedQueryParametersModel;
}

export interface DashboardSummary {
  pending_count: number;
  approved_count: number;
  rejected_count: number;
  total_items: number;
  entity_counts?: Record<string, number>;
}

export interface DataDiscoverySessionResponse {
  id: string;
  owner_id: string;
  research_space_id: string | null;
  name: string;
  current_parameters: AdvancedQueryParametersModel;
  selected_sources: string[];
  tested_sources: string[];
  total_tests_run: number;
  successful_tests: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  last_activity_at: string;
}

export interface DictionaryChangelogListResponse {
  changelog_entries: DictionaryChangelogResponse[];
  total: number;
}

export interface DictionaryChangelogResponse {
  id: number;
  table_name: string;
  record_id: string;
  action: string;
  before_snapshot: Record<string, unknown> | null;
  after_snapshot: Record<string, unknown> | null;
  changed_by: string | null;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryEntityTypeCreateRequest {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  external_ontology_ref?: string | null;
  expected_properties?: Record<string, unknown>;
  source_ref?: string | null;
}

export interface DictionaryEntityTypeListResponse {
  entity_types: DictionaryEntityTypeResponse[];
  total: number;
}

export interface DictionaryEntityTypeResponse {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  external_ontology_ref: string | null;
  expected_properties: Record<string, unknown>;
  description_embedding: number[] | null;
  embedded_at: string | null;
  embedding_model: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryMergeRequest {
  target_id: string;
  reason: string;
}

export interface DictionaryReembedRequest {
  model_name?: string | null;
  limit_per_dimension?: number | null;
  source_ref?: string | null;
}

export interface DictionaryReembedResponse {
  updated_records: number;
  model_name: string | null;
}

export interface DictionaryRelationSynonymCreateRequest {
  relation_type_id: string;
  synonym: string;
  source?: string | null;
  source_ref?: string | null;
}

export interface DictionaryRelationSynonymListResponse {
  relation_synonyms: DictionaryRelationSynonymResponse[];
  total: number;
}

export interface DictionaryRelationSynonymResponse {
  id: number;
  relation_type: string;
  synonym: string;
  source: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryRelationTypeCreateRequest {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  is_directional?: boolean;
  inverse_label?: string | null;
  source_ref?: string | null;
}

export interface DictionaryRelationTypeListResponse {
  relation_types: DictionaryRelationTypeResponse[];
  total: number;
}

export interface DictionaryRelationTypeResponse {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  is_directional: boolean;
  inverse_label: string | null;
  description_embedding: number[] | null;
  embedded_at: string | null;
  embedding_model: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionarySearchListResponse {
  results: DictionarySearchResultResponse[];
  total: number;
}

export interface DictionarySearchResultResponse {
  dimension: 'variables' | 'entity_types' | 'relation_types' | 'constraints';
  entry_id: string;
  display_name: string;
  description: string | null;
  domain_context: string | null;
  match_method: 'exact' | 'synonym' | 'fuzzy' | 'vector';
  similarity_score: number;
  metadata: Record<string, unknown>;
}

export interface DiscoveryPresetResponse {
  id: string;
  name: string;
  description: string | null;
  provider: 'pubmed';
  scope: 'user' | 'space';
  research_space_id: string | null;
  parameters: AdvancedQueryParametersModel;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface DiscoverySearchJobResponse {
  id: string;
  owner_id: string;
  session_id: string | null;
  provider: 'pubmed';
  status: 'queued' | 'running' | 'completed' | 'failed';
  query_preview: string;
  parameters: AdvancedQueryParametersModel;
  total_results: number;
  result_metadata: Record<string, unknown>;
  error_message: string | null;
  storage_key: string | null;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
}

export interface EntityResolutionPolicyListResponse {
  policies: EntityResolutionPolicyResponse[];
  total: number;
}

export interface EntityResolutionPolicyResponse {
  entity_type: string;
  policy_strategy: string;
  required_anchors: string[];
  auto_merge_threshold: number;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface ErrorDetail {
  field?: string | null;
  message: string;
  code?: string | null;
}

export interface ErrorResponse {
  error: string;
  message: string;
  details?: ErrorDetail[] | null;
  request_id?: string | null;
}

export interface EvidenceCreate {
  variant_id: string;
  phenotype_id: string;
  description: string;
  summary?: string | null;
  evidence_level?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  evidence_type?: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion';
  publication_id?: string | null;
  confidence_score?: number;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed?: boolean;
  review_date?: string | null;
  reviewer_notes?: string | null;
}

export interface EvidenceResponse {
  id: number;
  variant_id: string;
  phenotype_id: string;
  publication_id?: string | null;
  description: string;
  summary?: string | null;
  evidence_level: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  evidence_type: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion';
  confidence_score: number;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed: boolean;
  review_date?: string | null;
  reviewer_notes?: string | null;
  created_at: string;
  updated_at: string;
  variant?: VariantLinkSummary | null;
  phenotype?: PhenotypeSummary | null;
  publication?: PublicationSummary | null;
}

export interface EvidenceSummaryResponse {
  id?: number | null;
  evidence_level: string;
  evidence_type: string;
  description: string;
  reviewed: boolean;
}

export interface EvidenceUpdate {
  description?: string | null;
  summary?: string | null;
  evidence_level?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven' | null;
  evidence_type?: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion' | null;
  publication_id?: string | null;
  confidence_score?: number | null;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed?: boolean | null;
  review_date?: string | null;
  reviewer_notes?: string | null;
}

export interface ExecuteQueryTestRequest {
  session_id: string;
  catalog_entry_id: string;
  timeout_seconds?: number;
  parameters?: AdvancedQueryParameters | null;
}

export interface ExecuteTestRequest {
  catalog_entry_id: string;
  timeout_seconds?: number;
  parameters?: AdvancedQueryParametersModel | null;
}

export interface ExportEntityInfo {
  type: string;
  description: string;
}

export interface ExportOptionsResponse {
  entity_type: string;
  export_formats: string[];
  compression_formats: string[];
  info: Record<string, unknown>;
}

export interface ExportableEntitiesResponse {
  exportable_entities: ExportEntityInfo[];
  supported_formats: string[];
  supported_compression: string[];
  usage: UsageInfo;
}

export interface ExtractionFactResponse {
  fact_type: unknown;
  value: string;
  normalized_id?: string | null;
  source?: string | null;
  attributes?: Record<string, unknown> | null;
}

export interface GeneCreate {
  symbol: string;
  name?: string | null;
  description?: string | null;
  gene_type?: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown';
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
}

export interface GenePhenotypeSummary {
  phenotype_id: string;
  name: string;
}

export interface GeneResponse {
  id: number;
  gene_id: string;
  symbol: string;
  name?: string | null;
  description?: string | null;
  gene_type: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown';
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
  created_at: string;
  updated_at: string;
  variant_count?: number;
  phenotype_count?: number;
  variants?: VariantSummaryResponse[] | null;
  phenotypes?: GenePhenotypeSummary[] | null;
}

export interface GeneSummary {
  id?: number | null;
  gene_id?: string | null;
  symbol?: string | null;
  name?: string | null;
}

export interface GeneUpdate {
  name?: string | null;
  description?: string | null;
  gene_type?: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown' | null;
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
}

export interface GenerateHypothesesRequest {
  seed_entity_ids?: string[] | null;
  source_type?: string;
  relation_types?: string[] | null;
  max_depth?: number;
  max_hypotheses?: number;
  model_id?: string | null;
}

export interface GenerateHypothesesResponse {
  run_id: string;
  requested_seed_count: number;
  used_seed_count: number;
  candidates_seen: number;
  created_count: number;
  deduped_count: number;
  errors: string[];
  hypotheses: HypothesisResponse[];
}

export interface HealthComponent {
  status: string;
  message?: string | null;
  details?: Record<string, unknown> | null;
}

export interface HealthResponse {
  status: string;
  timestamp: string;
  version: string;
  uptime?: string | null;
  components?: Record<string, HealthComponent> | null;
}

export interface HypothesisListResponse {
  hypotheses: HypothesisResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface HypothesisResponse {
  claim_id: string;
  polarity: string;
  claim_status: string;
  validation_state: string;
  persistability: string;
  confidence: number;
  source_label: string | null;
  relation_type: string;
  target_label: string | null;
  claim_text: string | null;
  linked_relation_id: string | null;
  origin: string;
  seed_entity_ids: string[];
  supporting_provenance_ids: string[];
  reasoning_path_id: string | null;
  supporting_claim_ids: string[];
  direct_supporting_claim_ids: string[];
  transferred_supporting_claim_ids: string[];
  transferred_from_entities: string[];
  transfer_basis: string[];
  contradiction_claim_ids: string[];
  explanation: string | null;
  path_confidence: number | null;
  path_length: number | null;
  created_at: string;
  metadata: Record<string, unknown>;
}

export interface KernelClaimEvidenceListResponse {
  claim_id: string;
  evidence: KernelClaimEvidenceResponse[];
  total: number;
}

export interface KernelClaimEvidenceResponse {
  id: string;
  claim_id: string;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  agent_run_id?: string | null;
  sentence: string | null;
  sentence_source: string | null;
  sentence_confidence: string | null;
  sentence_rationale: string | null;
  figure_reference: string | null;
  table_reference: string | null;
  confidence: number;
  metadata: Record<string, unknown>;
  paper_links?: KernelRelationPaperLinkResponse[];
  created_at: string;
}

export interface KernelClaimMechanismChainResponse {
  root_claim: KernelRelationClaimResponse;
  max_depth: number;
  canonical_relations: KernelRelationResponse[];
  claims: KernelRelationClaimResponse[];
  claim_relations: ClaimRelationResponse[];
  participants: ClaimParticipantResponse[];
  evidence: KernelClaimEvidenceResponse[];
  counts: KernelGraphViewCountsResponse;
}

export interface KernelEntityCreateRequest {
  entity_type: string;
  display_label?: string | null;
  metadata?: Record<string, unknown>;
  identifiers?: Record<string, string>;
}

export interface KernelEntityEmbeddingRefreshRequest {
  entity_ids?: string[] | null;
  limit?: number;
  model_name?: string | null;
  embedding_version?: number | null;
}

export interface KernelEntityEmbeddingRefreshResponse {
  requested: number;
  processed: number;
  refreshed: number;
  unchanged: number;
  missing_entities: string[];
}

export interface KernelEntityListResponse {
  entities: KernelEntityResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelEntityResponse {
  id: string;
  research_space_id: string;
  entity_type: string;
  display_label: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelEntitySimilarityListResponse {
  source_entity_id: string;
  results: KernelEntitySimilarityResponse[];
  total: number;
  limit: number;
  min_similarity: number;
}

export interface KernelEntitySimilarityResponse {
  entity_id: string;
  entity_type: string;
  display_label?: string | null;
  similarity_score: number;
  score_breakdown: KernelEntitySimilarityScoreBreakdownResponse;
}

export interface KernelEntitySimilarityScoreBreakdownResponse {
  vector_score: number;
  graph_overlap_score: number;
}

export interface KernelEntityUpdateRequest {
  display_label?: string | null;
  metadata?: Record<string, unknown> | null;
  identifiers?: Record<string, string> | null;
}

export interface KernelEntityUpsertResponse {
  entity: KernelEntityResponse;
  created: boolean;
}

export interface KernelGraphDocumentCounts {
  entity_nodes: number;
  claim_nodes: number;
  evidence_nodes: number;
  canonical_edges: number;
  claim_participant_edges: number;
  claim_evidence_edges: number;
}

export interface KernelGraphDocumentEdge {
  id: string;
  resource_id?: string | null;
  kind: unknown;
  source_id: string;
  target_id: string;
  type_label: string;
  label: string;
  confidence?: number | null;
  curation_status?: string | null;
  claim_id?: string | null;
  canonical_relation_id?: string | null;
  evidence_id?: string | null;
  metadata?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelGraphDocumentMeta {
  mode: unknown;
  seed_entity_ids: string[];
  requested_depth: number;
  requested_top_k: number;
  pre_cap_entity_node_count: number;
  pre_cap_canonical_edge_count: number;
  truncated_entity_nodes: boolean;
  truncated_canonical_edges: boolean;
  included_claims: boolean;
  included_evidence: boolean;
  max_claims: number;
  evidence_limit_per_claim: number;
  counts: KernelGraphDocumentCounts;
}

export interface KernelGraphDocumentNode {
  id: string;
  resource_id: string;
  kind: unknown;
  type_label: string;
  label: string;
  confidence?: number | null;
  curation_status?: string | null;
  claim_status?: string | null;
  polarity?: string | null;
  canonical_relation_id?: string | null;
  metadata?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelGraphDocumentRequest {
  mode: unknown;
  seed_entity_ids?: string[];
  depth?: number;
  top_k?: number;
  relation_types?: string[] | null;
  curation_statuses?: string[] | null;
  max_nodes?: number;
  max_edges?: number;
  include_claims?: boolean;
  include_evidence?: boolean;
  max_claims?: number;
  evidence_limit_per_claim?: number;
}

export interface KernelGraphDocumentResponse {
  nodes: KernelGraphDocumentNode[];
  edges: KernelGraphDocumentEdge[];
  meta: KernelGraphDocumentMeta;
}

export interface KernelGraphDomainViewResponse {
  view_type: string;
  resource_id: string;
  entity: KernelEntityResponse | null;
  claim: KernelRelationClaimResponse | null;
  paper: KernelSourceDocumentResponse | null;
  canonical_relations: KernelRelationResponse[];
  claims: KernelRelationClaimResponse[];
  claim_relations: ClaimRelationResponse[];
  participants: ClaimParticipantResponse[];
  evidence: KernelClaimEvidenceResponse[];
  counts: KernelGraphViewCountsResponse;
}

export interface KernelGraphExportResponse {
  nodes: KernelEntityResponse[];
  edges: KernelRelationResponse[];
}

export interface KernelGraphSubgraphMeta {
  mode: unknown;
  seed_entity_ids: string[];
  requested_depth: number;
  requested_top_k: number;
  pre_cap_node_count: number;
  pre_cap_edge_count: number;
  truncated_nodes: boolean;
  truncated_edges: boolean;
}

export interface KernelGraphSubgraphRequest {
  mode: unknown;
  seed_entity_ids?: string[];
  depth?: number;
  top_k?: number;
  relation_types?: string[] | null;
  curation_statuses?: string[] | null;
  max_nodes?: number;
  max_edges?: number;
}

export interface KernelGraphSubgraphResponse {
  nodes: KernelEntityResponse[];
  edges: KernelRelationResponse[];
  meta: KernelGraphSubgraphMeta;
}

export interface KernelGraphViewCountsResponse {
  canonical_relations: number;
  claims: number;
  claim_relations: number;
  participants: number;
  evidence: number;
}

export interface KernelObservationCreateRequest {
  subject_id: string;
  variable_id: string;
  value: unknown;
  unit?: string | null;
  observed_at?: string | null;
  provenance_id?: string | null;
  confidence?: number;
}

export interface KernelObservationListResponse {
  observations: KernelObservationResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelObservationResponse {
  id: string;
  research_space_id: string;
  subject_id: string;
  variable_id: string;
  value_numeric: number | null;
  value_text: string | null;
  value_date: string | null;
  value_coded: string | null;
  value_boolean: boolean | null;
  value_json: unknown | null;
  unit: string | null;
  observed_at: string | null;
  provenance_id: string | null;
  confidence: number;
  created_at: string;
  updated_at: string;
}

export interface KernelProvenanceListResponse {
  provenance: KernelProvenanceResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelProvenanceResponse {
  id: string;
  research_space_id: string;
  source_type: string;
  source_ref: string | null;
  extraction_run_id: string | null;
  mapping_method: string | null;
  mapping_confidence: number | null;
  agent_model: string | null;
  raw_input: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}

export interface KernelReasoningPathDetailResponse {
  path: KernelReasoningPathResponse;
  steps: KernelReasoningPathStepResponse[];
  canonical_relations: KernelRelationResponse[];
  claims: KernelRelationClaimResponse[];
  claim_relations: ClaimRelationResponse[];
  participants: ClaimParticipantResponse[];
  evidence: KernelClaimEvidenceResponse[];
  counts: KernelGraphViewCountsResponse;
}

export interface KernelReasoningPathListResponse {
  paths: KernelReasoningPathResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelReasoningPathResponse {
  id: string;
  research_space_id: string;
  path_kind: string;
  status: string;
  start_entity_id: string;
  end_entity_id: string;
  root_claim_id: string;
  path_length: number;
  confidence: number;
  path_signature_hash: string;
  generated_by: string | null;
  generated_at: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelReasoningPathStepResponse {
  id: string;
  path_id: string;
  step_index: number;
  source_claim_id: string;
  target_claim_id: string;
  claim_relation_id: string;
  canonical_relation_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface KernelRelationClaimListResponse {
  claims: KernelRelationClaimResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelRelationClaimResponse {
  id: string;
  research_space_id: string;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  agent_run_id?: string | null;
  source_type: string;
  relation_type: string;
  target_type: string;
  source_label: string | null;
  target_label: string | null;
  confidence: number;
  validation_state: string;
  validation_reason: string | null;
  persistability: string;
  claim_status: string;
  polarity: string;
  claim_text: string | null;
  claim_section: string | null;
  linked_relation_id: string | null;
  metadata: Record<string, unknown>;
  triaged_by: string | null;
  triaged_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface KernelRelationClaimTriageRequest {
  claim_status: string;
}

export interface KernelRelationConflictListResponse {
  conflicts: KernelRelationConflictResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelRelationConflictResponse {
  relation_id: string;
  support_count: number;
  refute_count: number;
  support_claim_ids: string[];
  refute_claim_ids: string[];
}

export interface KernelRelationCreateRequest {
  source_id: string;
  relation_type: string;
  target_id: string;
  confidence?: number;
  evidence_summary?: string | null;
  evidence_sentence?: string | null;
  evidence_sentence_source?: string | null;
  evidence_sentence_confidence?: string | null;
  evidence_sentence_rationale?: string | null;
  evidence_tier?: string | null;
  provenance_id?: string | null;
  source_document_ref?: string | null;
}

export interface KernelRelationCurationUpdateRequest {
  curation_status: string;
}

export interface KernelRelationListResponse {
  relations: KernelRelationResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelRelationPaperLinkResponse {
  label: string;
  url: string;
  source: string;
}

export interface KernelRelationResponse {
  id: string;
  research_space_id: string;
  source_id: string;
  relation_type: string;
  target_id: string;
  confidence: number;
  aggregate_confidence: number;
  source_count: number;
  highest_evidence_tier: string | null;
  curation_status: string;
  evidence_summary?: string | null;
  evidence_sentence?: string | null;
  evidence_sentence_source?: string | null;
  evidence_sentence_confidence?: string | null;
  evidence_sentence_rationale?: string | null;
  paper_links?: KernelRelationPaperLinkResponse[];
  provenance_id: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface KernelRelationSuggestionConstraintCheckResponse {
  passed: boolean;
  source_entity_type: string;
  relation_type: string;
  target_entity_type: string;
}

export interface KernelRelationSuggestionListResponse {
  suggestions: KernelRelationSuggestionResponse[];
  total: number;
  limit_per_source: number;
  min_score: number;
}

export interface KernelRelationSuggestionRequest {
  source_entity_ids: string[];
  limit_per_source?: number;
  min_score?: number;
  allowed_relation_types?: string[] | null;
  target_entity_types?: string[] | null;
  exclude_existing_relations?: boolean;
}

export interface KernelRelationSuggestionResponse {
  source_entity_id: string;
  target_entity_id: string;
  relation_type: string;
  final_score: number;
  score_breakdown: KernelRelationSuggestionScoreBreakdownResponse;
  constraint_check: KernelRelationSuggestionConstraintCheckResponse;
}

export interface KernelRelationSuggestionScoreBreakdownResponse {
  vector_score: number;
  graph_overlap_score: number;
  relation_prior_score: number;
}

export interface KernelSourceDocumentResponse {
  id: string;
  research_space_id: string | null;
  source_id: string;
  external_record_id: string;
  source_type: string;
  document_format: string;
  enrichment_status: string;
  extraction_status: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface MechanismCreate {
  name: string;
  description: string;
  evidence_tier: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score?: number;
  source?: string;
  lifecycle_state?: 'draft' | 'reviewed' | 'canonical' | 'deprecated';
  protein_domains?: ProteinDomainPayload[];
  phenotype_ids: number[];
}

export interface MechanismResponse {
  id: number;
  name: string;
  description?: string | null;
  evidence_tier: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score: number;
  source: string;
  lifecycle_state: 'draft' | 'reviewed' | 'canonical' | 'deprecated';
  protein_domains: ProteinDomainPayload[];
  phenotype_ids: number[];
  phenotype_count: number;
  created_at: string;
  updated_at: string;
}

export interface MechanismUpdate {
  name?: string | null;
  description?: string | null;
  evidence_tier?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven' | null;
  confidence_score?: number | null;
  source?: string | null;
  lifecycle_state?: 'draft' | 'reviewed' | 'canonical' | 'deprecated' | null;
  protein_domains?: ProteinDomainPayload[] | null;
  phenotype_ids?: number[] | null;
}

export interface OrchestratedSessionState {
  session: DataDiscoverySessionResponse;
  capabilities: SourceCapabilitiesDTO;
  validation?: ValidationResultDTO;
  view_context: ViewContextDTO;
}

export interface PaginatedResponse<T = unknown> {
  items: T[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
  has_next: boolean;
  has_prev: boolean;
}

export interface PaginationParams {
  page?: number;
  per_page?: number;
  sort_by?: string | null;
  sort_order?: string;
}

export interface PhenotypeCategoryResult {
  category: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  total_results: number;
  results: PhenotypeResponse[];
}

export interface PhenotypeCreate {
  hpo_id: string;
  hpo_term: string;
  name: string;
  definition?: string | null;
  synonyms?: string[] | null;
  category?: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  parent_hpo_id?: string | null;
  is_root_term?: boolean;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
}

export interface PhenotypeEvidenceResponse {
  phenotype_id: number;
  total_count: number;
  evidence?: EvidenceSummaryResponse[];
}

export interface PhenotypeResponse {
  id: number;
  hpo_id: string;
  hpo_term: string;
  name: string;
  definition?: string | null;
  synonyms?: string[] | null;
  category: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  parent_hpo_id?: string | null;
  is_root_term: boolean;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  variant_count?: number;
  parent_phenotype?: PhenotypeSummary | null;
  child_phenotypes?: PhenotypeSummary[] | null;
  evidence?: EvidenceSummaryResponse[] | null;
}

export interface PhenotypeSearchResult {
  query: string;
  total_results: number;
  results: PhenotypeResponse[];
}

export interface PhenotypeStatisticsResponse {
  total_phenotypes: number;
  root_terms: number;
  phenotypes_with_evidence: number;
}

export interface PhenotypeSummary {
  id?: number | null;
  hpo_id?: string | null;
  name?: string | null;
}

export interface PhenotypeUpdate {
  name?: string | null;
  definition?: string | null;
  synonyms?: string[] | null;
  category?: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other' | null;
  parent_hpo_id?: string | null;
  is_root_term?: boolean | null;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
}

export interface ProteinDomainCoordinate {
  x: number;
  y: number;
  z: number;
  confidence?: number | null;
}

export interface ProteinDomainPayload {
  name: string;
  source_id?: string | null;
  start_residue: number;
  end_residue: number;
  domain_type?: unknown;
  description?: string | null;
  coordinates?: ProteinDomainCoordinate[] | null;
}

export interface PublicationCreate {
  title: string;
  authors: AuthorInfo[];
  journal: string;
  publication_year: number;
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  publication_type?: 'journal_article' | 'review_article' | 'case_report' | 'conference_abstract' | 'book_chapter' | 'thesis' | 'preprint';
  abstract?: string | null;
  keywords?: string[] | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed?: boolean;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access?: boolean;
}

export interface PublicationExtractionDocumentResponse {
  extraction_id: string;
  document_reference: string;
  url: string;
}

export interface PublicationExtractionResponse {
  id: string;
  publication_id?: number | null;
  pubmed_id?: string | null;
  source_id: string;
  ingestion_job_id: string;
  queue_item_id: string;
  status: 'completed' | 'failed' | 'skipped';
  extraction_version: number;
  processor_name: string;
  processor_version?: string | null;
  text_source: string;
  document_reference?: string | null;
  facts?: ExtractionFactResponse[];
  metadata?: Record<string, unknown>;
  extracted_at: string;
  created_at: string;
  updated_at: string;
}

export interface PublicationResponse {
  id: number;
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  title: string;
  authors: AuthorInfo[];
  journal: string;
  publication_year: number;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  publication_type: 'journal_article' | 'review_article' | 'case_report' | 'conference_abstract' | 'book_chapter' | 'thesis' | 'preprint';
  abstract?: string | null;
  keywords?: string[] | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed: boolean;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access: boolean;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  evidence?: EvidenceResponse[] | null;
}

export interface PublicationSummary {
  id?: number | null;
  title?: string | null;
  pubmed_id?: string | null;
  doi?: string | null;
}

export interface PublicationUpdate {
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  title?: string | null;
  authors?: AuthorInfo[] | null;
  abstract?: string | null;
  keywords?: string[] | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed?: boolean | null;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access?: boolean | null;
}

export interface PubmedDownloadRequestModel {
  job_id: string;
  article_id: string;
}

export interface QueryParameterCapabilities {
  supports_date_range?: boolean;
  supports_publication_types?: boolean;
  supports_language_filter?: boolean;
  supports_sort_options?: boolean;
  supports_additional_terms?: boolean;
  max_results_limit?: number;
  supported_storage_use_cases?: 'pdf' | 'export' | 'raw_source' | 'document_content' | 'backup'[];
  supports_variation_type?: boolean;
  supports_clinical_significance?: boolean;
  supports_review_status?: boolean;
  supports_organism?: boolean;
  discovery_defaults?: CatalogDiscoveryDefaults;
}

export interface QueryParameters {
  gene_symbol?: string | null;
  search_term?: string | null;
}

export interface QueryParametersModel {
  gene_symbol?: string | null;
  search_term?: string | null;
}

export interface QueryTestResultResponse {
  id: string;
  catalog_entry_id: string;
  session_id: string;
  parameters: AdvancedQueryParametersModel;
  status: 'pending' | 'success' | 'error' | 'timeout' | 'validation_failed';
  response_data: Record<string, unknown> | null;
  response_url: string | null;
  error_message: string | null;
  execution_time_ms: number | null;
  data_quality_score: number | null;
  started_at: string;
  completed_at: string | null;
}

export interface RelationConstraintListResponse {
  constraints: RelationConstraintResponse[];
  total: number;
}

export interface RelationConstraintResponse {
  id: number;
  source_type: string;
  relation_type: string;
  target_type: string;
  is_allowed: boolean;
  requires_evidence: boolean;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface RunPubmedSearchRequestModel {
  session_id?: string | null;
  parameters: AdvancedQueryParametersModel;
}

export interface SourceCapabilitiesDTO {
  supports_gene_search?: boolean;
  supports_term_search?: boolean;
  supported_parameters?: string[];
  max_results_limit?: number;
}

export interface SourceCatalogEntry {
  id: string;
  name: string;
  category: string;
  subcategory: string | null;
  description: string;
  source_type: 'file_upload' | 'api' | 'database' | 'web_scraping' | 'pubmed' | 'clinvar';
  param_type: 'gene' | 'term' | 'gene_and_term' | 'none' | 'api';
  is_active: boolean;
  requires_auth: boolean;
  usage_count: number;
  success_rate: number;
  tags: string[];
  capabilities: QueryParameterCapabilities;
}

export interface SourceCatalogResponse {
  id: string;
  name: string;
  category: string;
  subcategory: string | null;
  description: string;
  source_type: 'file_upload' | 'api' | 'database' | 'web_scraping' | 'pubmed' | 'clinvar';
  param_type: 'gene' | 'term' | 'gene_and_term' | 'none' | 'api';
  is_active: boolean;
  requires_auth: boolean;
  usage_count: number;
  success_rate: number;
  tags: string[];
  capabilities: QueryParameterCapabilities;
}

export interface StatementCreate {
  title: string;
  summary: string;
  evidence_tier?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score?: number;
  status?: 'draft' | 'under_review' | 'well_supported';
  source?: string;
  protein_domains?: ProteinDomainPayload[];
  phenotype_ids?: number[];
}

export interface StatementResponse {
  id: number;
  title: string;
  summary: string;
  evidence_tier: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  confidence_score: number;
  status: 'draft' | 'under_review' | 'well_supported';
  source: string;
  protein_domains: ProteinDomainPayload[];
  phenotype_ids: number[];
  phenotype_count: number;
  promoted_mechanism_id?: number | null;
  created_at: string;
  updated_at: string;
}

export interface StatementUpdate {
  title?: string | null;
  summary?: string | null;
  evidence_tier?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven' | null;
  confidence_score?: number | null;
  status?: 'draft' | 'under_review' | 'well_supported' | null;
  source?: string | null;
  protein_domains?: ProteinDomainPayload[] | null;
  phenotype_ids?: number[] | null;
  promoted_mechanism_id?: number | null;
}

export interface StorageOperationResponse {
  id: string;
  configuration_id: string;
  key: string;
  status: 'success' | 'failed' | 'pending';
  created_at: string;
  metadata: Record<string, unknown>;
}

export interface TransformRegistryListResponse {
  transforms: TransformRegistryResponse[];
  total: number;
}

export interface TransformRegistryResponse {
  id: string;
  input_unit: string;
  output_unit: string;
  category: string;
  input_data_type: string | null;
  output_data_type: string | null;
  implementation_ref: string;
  is_deterministic: boolean;
  is_production_allowed: boolean;
  test_input: unknown | null;
  expected_output: unknown | null;
  description: string | null;
  status: string;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface TransformVerificationResponse {
  transform_id: string;
  passed: boolean;
  message: string;
  actual_output: unknown | null;
  expected_output: unknown | null;
  checked_at: string;
}

export interface UpdateParametersRequest {
  parameters: AdvancedQueryParametersModel;
}

export interface UpdateSelectionRequest {
  source_ids?: string[];
}

export interface UsageInfo {
  endpoint: string;
  description: string;
}

export interface ValidationIssueDTO {
  code: string;
  message: string;
  severity?: string;
  field?: string | null;
}

export interface ValidationResultDTO {
  is_valid: boolean;
  issues?: ValidationIssueDTO[];
}

export interface ValueSetCreateRequest {
  id: string;
  variable_id: string;
  name: string;
  description?: string | null;
  external_ref?: string | null;
  is_extensible?: boolean;
  source_ref?: string | null;
}

export interface ValueSetItemActiveRequest {
  is_active: boolean;
  revocation_reason?: string | null;
}

export interface ValueSetItemCreateRequest {
  code: string;
  display_label: string;
  synonyms?: string[];
  external_ref?: string | null;
  sort_order?: number;
  is_active?: boolean;
  source_ref?: string | null;
}

export interface ValueSetItemListResponse {
  items: ValueSetItemResponse[];
  total: number;
}

export interface ValueSetItemResponse {
  id: number;
  value_set_id: string;
  code: string;
  display_label: string;
  synonyms: string[];
  external_ref: string | null;
  sort_order: number;
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface ValueSetListResponse {
  value_sets: ValueSetResponse[];
  total: number;
}

export interface ValueSetResponse {
  id: string;
  variable_id: string;
  variable_data_type: string;
  name: string;
  description: string | null;
  external_ref: string | null;
  is_extensible: boolean;
  created_by: string;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface VariableDefinitionCreateRequest {
  id: string;
  canonical_name: string;
  display_name: string;
  data_type: 'INTEGER' | 'FLOAT' | 'STRING' | 'DATE' | 'CODED' | 'BOOLEAN' | 'JSON';
  domain_context?: string;
  sensitivity?: 'PUBLIC' | 'INTERNAL' | 'PHI';
  preferred_unit?: string | null;
  constraints?: Record<string, unknown>;
  description?: string | null;
  source_ref?: string | null;
}

export interface VariableDefinitionListResponse {
  variables: VariableDefinitionResponse[];
  total: number;
}

export interface VariableDefinitionResponse {
  id: string;
  canonical_name: string;
  display_name: string;
  data_type: 'INTEGER' | 'FLOAT' | 'STRING' | 'DATE' | 'CODED' | 'BOOLEAN' | 'JSON';
  preferred_unit: string | null;
  constraints: Record<string, unknown>;
  domain_context: string;
  sensitivity: 'PUBLIC' | 'INTERNAL' | 'PHI';
  description: string | null;
  description_embedding: number[] | null;
  embedded_at: string | null;
  embedding_model: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface VariableDefinitionReviewStatusRequest {
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  revocation_reason?: string | null;
}

export interface VariableDefinitionRevokeRequest {
  reason: string;
}

export interface VariantCreate {
  gene_id: string;
  chromosome: string;
  position: number;
  reference_allele: string;
  alternate_allele: string;
  clinvar_id?: string | null;
  variant_id?: string | null;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type?: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown';
  clinical_significance?: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided';
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
}

export interface VariantLinkSummary {
  id?: number | null;
  variant_id?: string | null;
  clinvar_id?: string | null;
  gene_symbol?: string | null;
}

export interface VariantResponse {
  id: number;
  variant_id: string;
  clinvar_id?: string | null;
  gene_id: string;
  gene_symbol: string;
  chromosome: string;
  position: number;
  reference_allele: string;
  alternate_allele: string;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown';
  clinical_significance: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided';
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  gene?: GeneSummary | null;
  evidence?: EvidenceSummaryResponse[] | null;
}

export interface VariantSummaryResponse {
  variant_id: string;
  clinvar_id?: string | null;
  chromosome: string;
  position: number;
  clinical_significance?: string | null;
}

export interface VariantUpdate {
  clinvar_id?: string | null;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type?: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown' | null;
  clinical_significance?: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided' | null;
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
}

export interface ViewContextDTO {
  selected_count: number;
  total_available: number;
  can_run_search: boolean;
  categories?: Record<string, number>;
}
