"""Entity-recognition prompts."""

from src.infrastructure.llm.prompts.entity_recognition.clinvar import (
    CLINVAR_ENTITY_RECOGNITION_DISCOVERY_SYSTEM_PROMPT,
    CLINVAR_ENTITY_RECOGNITION_POLICY_SYSTEM_PROMPT,
    CLINVAR_ENTITY_RECOGNITION_SYSTEM_PROMPT,
)
from src.infrastructure.llm.prompts.entity_recognition.pubmed import (
    PUBMED_ENTITY_RECOGNITION_DISCOVERY_SYSTEM_PROMPT,
    PUBMED_ENTITY_RECOGNITION_POLICY_SYSTEM_PROMPT,
    PUBMED_ENTITY_RECOGNITION_SYSTEM_PROMPT,
)

__all__ = [
    "CLINVAR_ENTITY_RECOGNITION_DISCOVERY_SYSTEM_PROMPT",
    "CLINVAR_ENTITY_RECOGNITION_POLICY_SYSTEM_PROMPT",
    "CLINVAR_ENTITY_RECOGNITION_SYSTEM_PROMPT",
    "PUBMED_ENTITY_RECOGNITION_DISCOVERY_SYSTEM_PROMPT",
    "PUBMED_ENTITY_RECOGNITION_POLICY_SYSTEM_PROMPT",
    "PUBMED_ENTITY_RECOGNITION_SYSTEM_PROMPT",
]
