"""
Dictionary Seeder — loads JSON seed files into kernel tables.

Run via: python -m src.database.seeds.seeder
Or from Makefile: make seed-dictionary
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from sqlalchemy import inspect, text

from src.type_definitions.dictionary import get_constraint_schema_for_data_type

if TYPE_CHECKING:
    from sqlalchemy.orm import Session

    from src.type_definitions.common import JSONObject

logger = logging.getLogger(__name__)

SEEDS_DIR = Path(__file__).parent

_DATA_TYPE_HINTS: dict[str, tuple[str, str]] = {
    "INTEGER": ("int", "Whole-number value"),
    "FLOAT": ("float", "Decimal numeric value"),
    "STRING": ("str", "Free-form text"),
    "DATE": ("datetime", "Date/time value"),
    "CODED": ("str", "Enumerated coded value"),
    "BOOLEAN": ("bool", "True/False value"),
    "JSON": ("dict", "Structured JSON payload"),
}
_SENSITIVITY_DESCRIPTIONS: dict[str, str] = {
    "PUBLIC": "Data suitable for broad sharing",
    "INTERNAL": "Internal-only research data",
    "PHI": "Sensitive regulated patient data",
}


def _humanize(identifier: str) -> str:
    return " ".join(part.capitalize() for part in identifier.replace("_", " ").split())


def _table_exists(session: Session, table_name: str) -> bool:
    connection = session.connection()
    return inspect(connection).has_table(table_name)


def _ensure_data_type_reference(session: Session, data_type: str) -> None:
    if not _table_exists(session, "dictionary_data_types"):
        return

    normalized = data_type.strip().upper()
    constraint_schema = get_constraint_schema_for_data_type(normalized)
    hint, description = _DATA_TYPE_HINTS.get(
        normalized,
        ("str", "Autogenerated data type from seed input"),
    )
    session.execute(
        text(
            """
            INSERT INTO dictionary_data_types
                (id, display_name, python_type_hint, description, constraint_schema)
            SELECT :id, :display_name, :python_type_hint, :description, :constraint_schema
            WHERE NOT EXISTS (
                SELECT 1 FROM dictionary_data_types WHERE id = :id
            )
            """,
        ),
        {
            "id": normalized,
            "display_name": _humanize(normalized),
            "python_type_hint": hint,
            "description": description,
            "constraint_schema": json.dumps(constraint_schema),
        },
    )
    session.execute(
        text(
            """
            UPDATE dictionary_data_types
            SET constraint_schema = :constraint_schema
            WHERE id = :id
              AND (
                constraint_schema IS NULL
                OR constraint_schema = '{}'::jsonb
              )
            """,
        ),
        {
            "id": normalized,
            "constraint_schema": json.dumps(constraint_schema),
        },
    )


def _ensure_domain_context_reference(session: Session, domain_context: str) -> None:
    if not _table_exists(session, "dictionary_domain_contexts"):
        return

    normalized = domain_context.strip()
    if not normalized:
        return

    session.execute(
        text(
            """
            INSERT INTO dictionary_domain_contexts (id, display_name, description)
            SELECT :id, :display_name, :description
            WHERE NOT EXISTS (
                SELECT 1 FROM dictionary_domain_contexts WHERE id = :id
            )
            """,
        ),
        {
            "id": normalized,
            "display_name": _humanize(normalized),
            "description": "Autogenerated domain context from seed input",
        },
    )


def _ensure_sensitivity_reference(session: Session, sensitivity: str) -> None:
    if not _table_exists(session, "dictionary_sensitivity_levels"):
        return

    normalized = sensitivity.strip().upper()
    if not normalized:
        return

    session.execute(
        text(
            """
            INSERT INTO dictionary_sensitivity_levels (id, display_name, description)
            SELECT :id, :display_name, :description
            WHERE NOT EXISTS (
                SELECT 1 FROM dictionary_sensitivity_levels WHERE id = :id
            )
            """,
        ),
        {
            "id": normalized,
            "display_name": _humanize(normalized),
            "description": _SENSITIVITY_DESCRIPTIONS.get(
                normalized,
                "Autogenerated sensitivity level from seed input",
            ),
        },
    )


def _ensure_entity_type_reference(
    session: Session,
    *,
    entity_type: str,
    domain_context: str = "general",
) -> None:
    if not _table_exists(session, "dictionary_entity_types"):
        return

    _ensure_domain_context_reference(session, domain_context)
    normalized = entity_type.strip().upper()
    if not normalized:
        return

    session.execute(
        text(
            """
            INSERT INTO dictionary_entity_types (
                id, display_name, description, domain_context, expected_properties,
                created_by, review_status
            )
            SELECT :id, :display_name, :description, :domain_context, :expected_properties,
                   :created_by, :review_status
            WHERE NOT EXISTS (
                SELECT 1 FROM dictionary_entity_types WHERE id = :id
            )
            """,
        ),
        {
            "id": normalized,
            "display_name": _humanize(normalized),
            "description": "Autogenerated entity type from seed input",
            "domain_context": domain_context,
            "expected_properties": json.dumps({}),
            "created_by": "seed",
            "review_status": "ACTIVE",
        },
    )


def _ensure_relation_type_reference(
    session: Session,
    *,
    relation_type: str,
    domain_context: str = "general",
) -> None:
    if not _table_exists(session, "dictionary_relation_types"):
        return

    _ensure_domain_context_reference(session, domain_context)
    normalized = relation_type.strip().upper()
    if not normalized:
        return

    session.execute(
        text(
            """
            INSERT INTO dictionary_relation_types (
                id, display_name, description, domain_context, is_directional,
                created_by, review_status
            )
            SELECT :id, :display_name, :description, :domain_context, :is_directional,
                   :created_by, :review_status
            WHERE NOT EXISTS (
                SELECT 1 FROM dictionary_relation_types WHERE id = :id
            )
            """,
        ),
        {
            "id": normalized,
            "display_name": _humanize(normalized),
            "description": "Autogenerated relation type from seed input",
            "domain_context": domain_context,
            "is_directional": True,
            "created_by": "seed",
            "review_status": "ACTIVE",
        },
    )


def _load_json(filename: str) -> list[JSONObject]:
    """Load a JSON seed file from the seeds directory."""
    path = SEEDS_DIR / filename
    if not path.exists():
        logger.warning("Seed file not found: %s", path)
        return []
    with path.open() as f:
        data: list[JSONObject] = json.load(f)
        return data


def seed_variable_definitions(session: Session) -> int:
    """Seed variable_definitions table."""
    rows = _load_json("genomics_variables.json")
    if not rows:
        return 0

    count = 0
    for row in rows:
        data_type = str(row["data_type"]).strip().upper()
        domain_context = str(row.get("domain_context", "general")).strip() or "general"
        sensitivity = (
            str(row.get("sensitivity", "INTERNAL")).strip().upper() or "INTERNAL"
        )

        _ensure_data_type_reference(session, data_type)
        _ensure_domain_context_reference(session, domain_context)
        _ensure_sensitivity_reference(session, sensitivity)

        existing = session.execute(
            text("SELECT 1 FROM variable_definitions WHERE id = :id"),
            {"id": row["id"]},
        ).fetchone()
        if existing:
            continue

        session.execute(
            text(
                """
                INSERT INTO variable_definitions
                    (id, canonical_name, display_name, data_type,
                     preferred_unit, constraints, domain_context,
                     sensitivity, description)
                VALUES
                    (:id, :canonical_name, :display_name, :data_type,
                     :preferred_unit, :constraints, :domain_context,
                     :sensitivity, :description)
            """,
            ),
            {
                "id": row["id"],
                "canonical_name": row["canonical_name"],
                "display_name": row["display_name"],
                "data_type": data_type,
                "preferred_unit": row.get("preferred_unit"),
                "constraints": json.dumps(row.get("constraints", {})),
                "domain_context": domain_context,
                "sensitivity": sensitivity,
                "description": row.get("description"),
            },
        )
        count += 1

    session.commit()
    logger.info("Seeded %d variable definitions", count)
    return count


def seed_variable_synonyms(session: Session) -> int:
    """Seed variable_synonyms table."""
    rows = _load_json("variable_synonyms.json")
    if not rows:
        return 0

    count = 0
    for row in rows:
        synonym = str(row["synonym"]).lower()
        conflicting = session.execute(
            text(
                "SELECT variable_id FROM variable_synonyms "
                "WHERE synonym = :syn AND variable_id <> :vid "
                "AND is_active IS TRUE "
                "LIMIT 1",
            ),
            {"syn": synonym, "vid": row["variable_id"]},
        ).fetchone()
        if conflicting:
            msg = (
                f"Synonym '{synonym}' is already mapped to variable "
                f"'{conflicting[0]}'"
            )
            raise ValueError(msg)

        existing = session.execute(
            text(
                "SELECT 1 FROM variable_synonyms "
                "WHERE variable_id = :vid AND synonym = :syn",
            ),
            {"vid": row["variable_id"], "syn": synonym},
        ).fetchone()
        if existing:
            continue

        session.execute(
            text(
                """
                INSERT INTO variable_synonyms (variable_id, synonym, source)
                VALUES (:variable_id, :synonym, :source)
            """,
            ),
            {
                "variable_id": row["variable_id"],
                "synonym": synonym,
                "source": row.get("source"),
            },
        )
        count += 1

    session.commit()
    logger.info("Seeded %d variable synonyms", count)
    return count


def seed_entity_resolution_policies(session: Session) -> int:
    """Seed entity_resolution_policies table."""
    rows = _load_json("entity_types.json")
    if not rows:
        return 0

    now = datetime.now(UTC)
    count = 0
    for row in rows:
        entity_type = str(row["entity_type"]).strip().upper()
        _ensure_entity_type_reference(
            session,
            entity_type=entity_type,
            domain_context="genomics",
        )

        existing = session.execute(
            text("SELECT 1 FROM entity_resolution_policies WHERE entity_type = :et"),
            {"et": entity_type},
        ).fetchone()
        if existing:
            continue

        session.execute(
            text(
                """
                INSERT INTO entity_resolution_policies
                    (entity_type, policy_strategy, required_anchors,
                     auto_merge_threshold, created_at, updated_at)
                VALUES
                    (:entity_type, :policy_strategy, :required_anchors,
                     :auto_merge_threshold, :created_at, :updated_at)
            """,
            ),
            {
                "entity_type": entity_type,
                "policy_strategy": row["policy_strategy"],
                "required_anchors": json.dumps(row.get("required_anchors", [])),
                "auto_merge_threshold": row.get("auto_merge_threshold", 1.0),
                "created_at": now,
                "updated_at": now,
            },
        )
        count += 1

    session.commit()
    logger.info("Seeded %d entity resolution policies", count)
    return count


def seed_relation_constraints(session: Session) -> int:
    """Seed relation_constraints table."""
    rows = _load_json("relation_constraints.json")
    if not rows:
        return 0

    count = 0
    for row in rows:
        source_type = str(row["source_type"]).strip().upper()
        relation_type = str(row["relation_type"]).strip().upper()
        target_type = str(row["target_type"]).strip().upper()

        _ensure_entity_type_reference(
            session,
            entity_type=source_type,
            domain_context="genomics",
        )
        _ensure_entity_type_reference(
            session,
            entity_type=target_type,
            domain_context="genomics",
        )
        _ensure_relation_type_reference(
            session,
            relation_type=relation_type,
            domain_context="genomics",
        )

        existing = session.execute(
            text(
                "SELECT 1 FROM relation_constraints "
                "WHERE source_type = :st AND relation_type = :rt "
                "AND target_type = :tt",
            ),
            {
                "st": source_type,
                "rt": relation_type,
                "tt": target_type,
            },
        ).fetchone()
        if existing:
            continue

        session.execute(
            text(
                """
                INSERT INTO relation_constraints
                    (source_type, relation_type, target_type,
                     is_allowed, requires_evidence)
                VALUES
                    (:source_type, :relation_type, :target_type,
                     :is_allowed, :requires_evidence)
            """,
            ),
            {
                "source_type": source_type,
                "relation_type": relation_type,
                "target_type": target_type,
                "is_allowed": row.get("is_allowed", True),
                "requires_evidence": row.get("requires_evidence", True),
            },
        )
        count += 1

    session.commit()
    logger.info("Seeded %d relation constraints", count)
    return count


def seed_all(session: Session) -> dict[str, int]:
    """Run all seeders. Returns counts per table."""
    results = {
        "variable_definitions": seed_variable_definitions(session),
        "variable_synonyms": seed_variable_synonyms(session),
        "entity_resolution_policies": seed_entity_resolution_policies(session),
        "relation_constraints": seed_relation_constraints(session),
    }
    total = sum(results.values())
    logger.info("Dictionary seeding complete: %d total rows", total)
    return results


if __name__ == "__main__":
    import sys

    from src.database.session import SessionLocal

    logging.basicConfig(level=logging.INFO)

    SessionFactory = SessionLocal

    with SessionFactory() as session:
        results = seed_all(session)
        logger.info("Seeding results:")
        for table, count in results.items():
            logger.info("  %s: %d rows", table, count)
        logger.info("  TOTAL: %d rows", sum(results.values()))
        sys.exit(0)
