"""Compatibility re-export for kernel graph API schemas."""

from __future__ import annotations

from src.type_definitions.graph_api_schemas.kernel_entity_schemas import (
    KernelEntityCreateRequest,
    KernelEntityEmbeddingRefreshRequest,
    KernelEntityEmbeddingRefreshResponse,
    KernelEntityListResponse,
    KernelEntityResponse,
    KernelEntitySimilarityListResponse,
    KernelEntitySimilarityResponse,
    KernelEntitySimilarityScoreBreakdownResponse,
    KernelEntityUpdateRequest,
    KernelEntityUpsertResponse,
    KernelRelationSuggestionConstraintCheckResponse,
    KernelRelationSuggestionListResponse,
    KernelRelationSuggestionRequest,
    KernelRelationSuggestionResponse,
    KernelRelationSuggestionScoreBreakdownResponse,
)
from src.type_definitions.graph_api_schemas.kernel_graph_schemas import (
    KernelGraphDocumentCounts,
    KernelGraphDocumentEdge,
    KernelGraphDocumentMeta,
    KernelGraphDocumentNode,
    KernelGraphDocumentRequest,
    KernelGraphDocumentResponse,
    KernelGraphExportResponse,
    KernelGraphSubgraphMeta,
    KernelGraphSubgraphRequest,
    KernelGraphSubgraphResponse,
    KernelProvenanceListResponse,
    KernelProvenanceResponse,
)
from src.type_definitions.graph_api_schemas.kernel_observation_schemas import (
    KernelObservationCreateRequest,
    KernelObservationListResponse,
    KernelObservationResponse,
)
from src.type_definitions.graph_api_schemas.kernel_relation_schemas import (
    KernelClaimEvidenceListResponse,
    KernelClaimEvidenceResponse,
    KernelRelationClaimCreateRequest,
    KernelRelationClaimListResponse,
    KernelRelationClaimResponse,
    KernelRelationClaimTriageRequest,
    KernelRelationConflictListResponse,
    KernelRelationConflictResponse,
    KernelRelationCreateRequest,
    KernelRelationCurationUpdateRequest,
    KernelRelationListResponse,
    KernelRelationPaperLinkResponse,
    KernelRelationResponse,
)

__all__ = [
    "KernelClaimEvidenceListResponse",
    "KernelClaimEvidenceResponse",
    "KernelEntityCreateRequest",
    "KernelEntityEmbeddingRefreshRequest",
    "KernelEntityEmbeddingRefreshResponse",
    "KernelEntityListResponse",
    "KernelEntityResponse",
    "KernelEntitySimilarityListResponse",
    "KernelEntitySimilarityResponse",
    "KernelEntitySimilarityScoreBreakdownResponse",
    "KernelEntityUpdateRequest",
    "KernelEntityUpsertResponse",
    "KernelGraphDocumentCounts",
    "KernelGraphDocumentEdge",
    "KernelGraphDocumentMeta",
    "KernelGraphDocumentNode",
    "KernelGraphDocumentRequest",
    "KernelGraphDocumentResponse",
    "KernelGraphExportResponse",
    "KernelGraphSubgraphMeta",
    "KernelGraphSubgraphRequest",
    "KernelGraphSubgraphResponse",
    "KernelObservationCreateRequest",
    "KernelObservationListResponse",
    "KernelObservationResponse",
    "KernelProvenanceListResponse",
    "KernelProvenanceResponse",
    "KernelRelationClaimCreateRequest",
    "KernelRelationClaimListResponse",
    "KernelRelationClaimResponse",
    "KernelRelationClaimTriageRequest",
    "KernelRelationConflictListResponse",
    "KernelRelationConflictResponse",
    "KernelRelationCreateRequest",
    "KernelRelationCurationUpdateRequest",
    "KernelRelationListResponse",
    "KernelRelationPaperLinkResponse",
    "KernelRelationResponse",
    "KernelRelationSuggestionConstraintCheckResponse",
    "KernelRelationSuggestionListResponse",
    "KernelRelationSuggestionRequest",
    "KernelRelationSuggestionResponse",
    "KernelRelationSuggestionScoreBreakdownResponse",
]
